# Generated by Django 4.2.6 on 2023-11-27 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Myapp',
        ),
    ]
